# Generated by Django 4.2.3 on 2023-08-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_classifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('hidden_layer_sizes', models.CharField(default='100', max_length=100)),
                ('activation', models.CharField(choices=[('relu', 'relu'), ('identity', 'identity'), ('logistic', 'logistic'), ('tanh', 'tanh')], default='relu', max_length=8)),
                ('solver', models.CharField(choices=[('adam', 'adam'), ('sgd', 'sgd'), ('lbfgs', 'lbfgs')], default='adam', max_length=5)),
                ('alpha', models.FloatField(default=0.0001)),
                ('batch_size', models.PositiveIntegerField(blank=True, null=True)),
                ('learning_rate', models.CharField(choices=[('constant', 'constant'), ('invscaling', 'invscaling'), ('adaptive', 'adaptive')], default='constant', max_length=10)),
                ('learning_rate_init', models.FloatField(verbose_name=0.001)),
                ('power_t', models.FloatField(default=0.5)),
                ('max_iter', models.PositiveIntegerField(default=200)),
                ('shuffle', models.BooleanField(default=True)),
                ('random_state', models.PositiveIntegerField(blank=True, null=True)),
                ('tol', models.FloatField(default=0.0001)),
                ('verbose', models.BooleanField(default=False)),
                ('warm_start', models.BooleanField(default=False)),
                ('momentum', models.FloatField(default=0.9)),
                ('nesterovs_momentum', models.BooleanField(default=True)),
                ('early_stopping', models.BooleanField(default=False)),
                ('validation_fraction', models.FloatField(default=0.1)),
                ('beta_1', models.FloatField(default=0.9)),
                ('beta_2', models.FloatField(default=0.999)),
                ('epsilon', models.FloatField(default=1e-08)),
                ('n_iter_no_change', models.PositiveIntegerField(default=10)),
                ('max_fun', models.PositiveIntegerField(default=15000)),
            ],
        ),
        migrations.DeleteModel(
            name='Classifier',
        ),
    ]
