# Generated by Django 4.2.3 on 2023-08-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0003_classifierconfig_delete_classifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifierconfig',
            name='learning_rate_init',
            field=models.FloatField(default=0.001),
        ),
        migrations.AlterField(
            model_name='classifierconfig',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ClassifierSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='brain.classifierconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ClassifierFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='brain.classifierconfig')),
            ],
        ),
    ]
