# Generated by Django 4.2.3 on 2023-08-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0004_alter_classifierconfig_learning_rate_init_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.IntegerField()),
                ('pages_visited', models.IntegerField()),
                ('conversion_target_a', models.IntegerField(default=0)),
                ('conversion_target_b', models.IntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='brain.classifierconfig')),
            ],
        ),
        migrations.DeleteModel(
            name='VisitorBehavior',
        ),
    ]
