# Generated by Django 4.2.3 on 2023-08-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0005_datapoint_delete_visitorbehavior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='conversion_target_a',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='conversion_target_b',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='pages_visited',
        ),
        migrations.RemoveField(
            model_name='datapoint',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='features',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapoint',
            name='samples',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
