# Generated by Django 4.2.3 on 2023-08-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0006_remove_datapoint_conversion_target_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
