# Generated by Django 4.2.3 on 2023-08-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0007_datapoint_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifierconfig',
            name='neural_net',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='classifierconfig',
            name='scaler_net',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
