# Generated by Django 4.2.3 on 2023-08-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0009_rename_scaler_net_classifierconfig_scaler'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifierconfig',
            name='training_warnings',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='brain.classifierconfig'),
        ),
    ]
